<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Array_Transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A=np.arange(6).reshape(3,2) # reshape() funksiyasi 2 o'lchamli array yaratadi
A

array([[0, 1],
       [2, 3],
       [4, 5]])

**Transpose**

In [4]:
A.T # A.T bunda A massiv transpose boladi

array([[0, 2, 4],
       [1, 3, 5]])

**swaping axes** xususiy transpose

In [5]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.swapaxes(1,0)# o'qlar joyi almashyabdi

array([[0, 2, 4],
       [1, 3, 5]])

In [25]:
B=np.arange(3,12).reshape(3,3) # bunda ham arrayni transpose qilib beryabdi
B.swapaxes(1,0)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**transpose**ning ishlatilishi A*A(Transpose)

In [26]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
np.dot(A,A.T)#  bunda A massivni uning transposiga ko'paytiryabdi

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])