<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Boolean_indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
ismlar=np.array(['Munira','Nigora','Malika','Dilrabo','Fotima','Munira'])
ismlar

array(['Munira', 'Nigora', 'Malika', 'Dilrabo', 'Fotima', 'Munira'],
      dtype='<U7')

In [31]:
 #data
data=np.random.randn(6,5)
data

array([[-0.44748601,  0.14739917, -0.75472348, -0.80018541, -1.07041611],
       [-0.47855122,  1.47523039,  1.46856463, -1.95180275, -0.55833504],
       [ 0.12667421,  0.16034526, -0.63463719, -0.49110351,  1.11233183],
       [ 0.98113201, -2.30702262,  1.67291106,  1.40866116,  0.44858704],
       [ 0.23033331,  0.82359609,  0.76201204, -0.95394662,  0.38646864],
       [ 1.17958416,  0.4676683 ,  0.23742926,  0.26109178, -1.01872254]])

In [4]:
ismlar=='Nigora' #Bolean indekslash

array([False,  True, False, False, False, False])

In [6]:
data[ismlar=='Nigora'] #Nigoraga tegishli malumotlarni ajratib oladi

array([[0.90176198, 0.60881171, 0.02345458, 0.4066302 , 0.53447163]])

In [8]:
data[ismlar!='Munira'] #Muniraga tegishli bo'lmagan barcha malumotlarni ajratib oladi

array([[0.90176198, 0.60881171, 0.02345458, 0.4066302 , 0.53447163],
       [0.98720238, 0.58598217, 0.51770044, 0.59859099, 0.69757473],
       [0.50608718, 0.76434295, 0.34994626, 0.47170226, 0.44615714],
       [0.82042644, 0.24861999, 0.06939092, 0.40620189, 0.39683302]])

In [9]:
data[~(ismlar=='Munira')] #Yuqoridagi ceil bilan bir xil

array([[0.90176198, 0.60881171, 0.02345458, 0.4066302 , 0.53447163],
       [0.98720238, 0.58598217, 0.51770044, 0.59859099, 0.69757473],
       [0.50608718, 0.76434295, 0.34994626, 0.47170226, 0.44615714],
       [0.82042644, 0.24861999, 0.06939092, 0.40620189, 0.39683302]])

In [14]:
data[ismlar=='Munira',2:4]

array([[0.72929462, 0.87478453],
       [0.53062772, 0.88243911]])

In [23]:
data[(ismlar=='Munira') | (ismlar=='Nigora')] # | operatori or operatoriga teng kuchli

array([[0.66671222, 0.07362336, 0.72929462, 0.87478453, 0.42102279],
       [0.90176198, 0.60881171, 0.02345458, 0.4066302 , 0.53447163],
       [0.69439357, 0.8508202 , 0.53062772, 0.88243911, 0.87632555]])

In [32]:
data

array([[-0.44748601,  0.14739917, -0.75472348, -0.80018541, -1.07041611],
       [-0.47855122,  1.47523039,  1.46856463, -1.95180275, -0.55833504],
       [ 0.12667421,  0.16034526, -0.63463719, -0.49110351,  1.11233183],
       [ 0.98113201, -2.30702262,  1.67291106,  1.40866116,  0.44858704],
       [ 0.23033331,  0.82359609,  0.76201204, -0.95394662,  0.38646864],
       [ 1.17958416,  0.4676683 ,  0.23742926,  0.26109178, -1.01872254]])

In [33]:
data[data<0]=0
data

array([[0.        , 0.14739917, 0.        , 0.        , 0.        ],
       [0.        , 1.47523039, 1.46856463, 0.        , 0.        ],
       [0.12667421, 0.16034526, 0.        , 0.        , 1.11233183],
       [0.98113201, 0.        , 1.67291106, 1.40866116, 0.44858704],
       [0.23033331, 0.82359609, 0.76201204, 0.        , 0.38646864],
       [1.17958416, 0.4676683 , 0.23742926, 0.26109178, 0.        ]])