<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
x=np.array([[1.,2.,3.],[1.,1.,1.]])
y=np.array([[4.,5.,6.],[10.,11.,12.]])

In [6]:
x+y

array([[ 5.,  7.,  9.],
       [11., 12., 13.]])

In [8]:
y-x

array([[ 3.,  3.,  3.],
       [ 9., 10., 11.]])

In [9]:
x*y

array([[ 4., 10., 18.],
       [10., 11., 12.]])

In [10]:
y/x

array([[ 4. ,  2.5,  2. ],
       [10. , 11. , 12. ]])

In [11]:
x1=np.array([[1,2,3],[4,5,6]])
y1=np.array([[1,2],[2,3],[4,5]])

In [13]:
x1.dot(y1)

array([[17, 23],
       [38, 53]])

In [14]:
np.dot(x1,y1)

array([[17, 23],
       [38, 53]])

In [15]:
y1.dot(x1)

array([[ 9, 12, 15],
       [14, 19, 24],
       [24, 33, 42]])