<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
data=[1,2,3,4]
arr=np.array(data)
arr

array([1, 2, 3, 4])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr9d=np.zeros((2,2,2,2,2,2,2,2,2))

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arrs=np.array([1,2,3,4])
arrs.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
vektor=np.zeros(12)
vektor[5]=1
vektor

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
vektor1=np.arange(20,60)
vektor1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
vektor2=np.random.randn(10)
vektor2

array([ 0.06847923, -0.36545968,  0.2517637 , -1.08980178,  1.24631001,
        0.076146  , -0.77548287, -0.97990112,  0.42436175, -0.25170609])

In [ ]:
vektor2[::-1]

array([-0.25170609,  0.42436175, -0.97990112, -0.77548287,  0.076146  ,
        1.24631001, -1.08980178,  0.2517637 , -0.36545968,  0.06847923])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


In [ ]:
elements=np.arange(12,21)
arr3=elements.reshape(3,3)
arr3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr=np.array([3,7,0,0,9,0])
x=0
ls=[]
for i in arr:
  if i!=0:
    ls.append(x)
  x=x+1
ls

[0, 1, 4]

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
from numpy.random import default_rng
default_rng(42).random((2,2,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803]],

       [[0.09417735, 0.97562235],
        [0.7611397 , 0.78606431]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr99=np.random.random((9,9))
arr99

array([[0.87152485, 0.533338  , 0.51622785, 0.65661381, 0.62979847,
        0.93108953, 0.11139395, 0.68909303, 0.45259508],
       [0.62534476, 0.29532437, 0.13722675, 0.86676883, 0.11976609,
        0.21449236, 0.74639418, 0.48814879, 0.79928862],
       [0.91171104, 0.56016753, 0.29649608, 0.95272425, 0.32298655,
        0.25494213, 0.36740582, 0.61259589, 0.50005472],
       [0.17415205, 0.3120092 , 0.39758939, 0.42138342, 0.69909975,
        0.3767799 , 0.16512868, 0.74695369, 0.41676927],
       [0.69175907, 0.86883198, 0.28271849, 0.78911709, 0.26458573,
        0.29542403, 0.58651029, 0.79288108, 0.29484708],
       [0.62277481, 0.07611992, 0.04844072, 0.08787911, 0.64319439,
        0.86692126, 0.12946765, 0.30654383, 0.22092921],
       [0.59626949, 0.8890247 , 0.21496966, 0.48272518, 0.73924705,
        0.10127711, 0.51250602, 0.5904259 , 0.33064908],
       [0.12805153, 0.98518445, 0.37464798, 0.56838033, 0.37165346,
        0.05965235, 0.61098742, 0.12418542, 0.08273466],


In [ ]:
np.min(arr99)

0.04844072119707743

In [ ]:
np.max(arr99)

0.9851844517422083

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr141=np.random.random((6,3))
arr142=np.random.random((3,4))
arr141.dot(arr142)

array([[1.02643172, 1.28856403, 0.861596  , 1.21819943],
       [0.9696224 , 1.05289104, 0.97727554, 1.04428987],
       [1.17340655, 1.35095715, 1.13414521, 1.28697704],
       [0.64033156, 0.56586106, 0.81723632, 0.56454968],
       [0.91442804, 0.82003866, 1.14057797, 0.82788727],
       [0.77899898, 0.91508985, 0.76050242, 0.84168612]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))

9


In [ ]:
from numpy import *
print(sum(range(5),-1))

array([], dtype=int64)

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
arr161=np.random.random(4)
arr162=np.random.random(4)

In [ ]:
arr161

array([0.99231678, 0.72961273, 0.32799908, 0.69938518])

In [ ]:
arr162

array([0.84718731, 0.33435452, 0.76246203, 0.9239643 ])

In [ ]:
arr161>arr162

array([ True,  True, False, False])

In [ ]:
arr161>=arr162

array([ True,  True, False, False])

In [ ]:
arr161<arr162

array([False, False,  True,  True])

In [ ]:
arr161<=arr162

array([False, False,  True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-89-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-91-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-91-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-91-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr171=np.array([1,2,3,4,5,6])
arr172=np.array([4,5,6,7,8,9])
np.intersect1d(arr171,arr172)

array([4, 5, 6])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr191=np.random.uniform(1,10,size=5)
arr191

array([4.64461421, 9.26018427, 9.38548569, 6.04836575, 5.86003197])

In [ ]:
ls=[(x-(x%1))  for x in arr191 if x>0]
ls

[4.0, 9.0, 9.0, 6.0, 5.0]

In [ ]:
ls1=np.floor(arr191)
ls1

array([4., 9., 9., 6., 5.])

In [ ]:
arr191.astype(int)

array([4, 9, 9, 6, 5])

In [ ]:
ls2=np.trunc(arr191)
ls2

array([4., 9., 9., 6., 5.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr201=np.arange(0,3)
arr20=np.repeat(arr201,3).reshape(3,3)
arr20

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
vektor21=np.random.randint(1,100,size=10)
vektor21

array([49, 50, 70, 53, 50, 80, 44, 30, 46, 87])

In [ ]:
np.sort(vektor21)

array([30, 44, 46, 49, 50, 50, 53, 70, 80, 87])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A=np.array([1,2,3,4,5,6])
B=np.array([1,2,5,7,8,0])
np.array_equal(A,B)

False

In [ ]:
np.allclose(A,B)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
mat1=np.ones(shape=(6,3))
mat2=np.ones(shape=(3,4))
np.dot(mat1,mat2)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
mat2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [5]:
vektor24=np.array([2,5,1,9,23])
vektor24[np.argmax(vektor24)]=0
vektor24

array([2, 5, 1, 9, 0])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [16]:
bugun=np.datetime64('2024-12-17')
kecha=np.timedelta64(-1,'D')+bugun
ertaga=np.timedelta64(1,'D')+bugun

In [17]:
kecha

numpy.datetime64('2024-12-16')

In [18]:
ertaga

numpy.datetime64('2024-12-18')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [20]:
np.arange('2016-01','2016-02',dtype='datetime64[D]')

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [27]:
arr27=np.random.uniform(1,100,size=5)
arr27

array([57.17560662, 82.53537205, 51.06769892, 53.45903341, 82.97044092])

In [33]:
np.array(arr27-(arr27%1))

array([57., 82., 51., 53., 82.])

In [32]:
np.floor(arr27)

array([57., 82., 51., 53., 82.])

In [30]:
arr27.astype(int)

array([57, 82, 51, 53, 82])

In [31]:
np.trunc(arr27)

array([57., 82., 51., 53., 82.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [39]:
m1=np.random.random(6)
m2=np.random.random(6)

In [52]:
yig=np.add.reduce(m1)
yig+=np.add.reduce(m2)
yig

4.129020561388302

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [61]:
arr29=np.array([1,2,3,4,5])
result=[]
for value in arr29:
  result.append(value)
  result.extend([0,0,0])
result=result[:-3]
result

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [82]:
from numpy.lib.stride_tricks import as_strided
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b=as_strided(a, shape=(11,4), strides=(8,8))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [88]:
m31=np.array([1,2,3,4,5,6,7,8,9,1,4,5,7,6,7])
a=np.bincount(m31)
np.where(a>1)

(array([1, 4, 5, 6, 7]),)

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

Biror bir massiv kiriting va uni kamayish tartibida tartiblang

In [89]:
m32=np.random.randint(1,100,size=12)
m32

array([35, 91, 79, 87, 95,  2, 77, 68, 64, 67, 28, 21])

In [91]:
-np.sort(-m32)

array([95, 91, 87, 79, 77, 68, 67, 64, 35, 28, 21,  2])