<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/FayllarNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data',arr)

In [5]:
arr1=np.load('data.npy')
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2=np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.savez('arrays', a=arr, b=arr2)

In [8]:
arrays=np.load('arrays.npz')

In [9]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.savez_compressed('arrays_comp',a=arr, b=arr2)

In [12]:
arr_comp=np.load('arrays_comp.npz')

In [13]:
arr_comp['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr_comp['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])