<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Indekslash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

In [2]:
arr=np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
arr[3:5]

array([40, 50])

In [4]:
sliced_arr=arr[3:5]
sliced_arr

array([40, 50])

In [5]:
sliced_arr[:]=0 #  bunda slcied arrayimizni barcha elementalri 0 ga teng boldi
sliced_arr

array([0, 0])

In [6]:
arr # silced arrayga kiritilgan o'zgarish tasir qildi

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

**copy()**

In [12]:
arr1=np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
sliced_arr1=arr1[3:5].copy() # array1 dan nusxa olindi
sliced_arr1[:]=0
sliced_arr1

array([0, 0])

In [14]:
arr1 #nusxa olingani uchun sliced_arr dagi o'zgarish tasir qilmadi

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

**Ikki o'lchamli massiv**

In [32]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[2,2] # ikki o'lchamli arraydan indeks orqali bitta element tanlash

9

In [38]:
sl_arr=arr2d[1:3,1:3] # ikki o'lchamli arrayni kesish
sl_arr

array([[5, 6],
       [8, 9]])

**Uch o'lchamli massiv**

In [43]:
arr3d=np.array([[[1,2,3],
        [4,5,6],
        [7,8,9]],
       [[1,2,3],
        [4,5,6],
        [7,8,9]],
       [[1,2,3],
        [4,5,6],
        [7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [44]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr3d[1][2,2]

9

In [48]:
arr3d[2][1,1:]

array([5, 6])