<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Mantiqiy_shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**where** mantiqiy shart operatori

In [2]:
arr1=np.array([1.1,1.2,1.3,1.4,1.5])
arr2=np.array([2.1,2.2,2.3,2.4,2.5])

In [3]:
cond=np.array([True,False,True,False,False])

In [4]:
np.where(cond,arr1,arr2)

array([1.1, 2.2, 1.3, 2.4, 2.5])

In [8]:
arr=np.random.randn(4,4)
arr

array([[ 0.04469635,  0.4287483 , -0.4355471 ,  1.02328452],
       [-0.0242017 ,  0.07027693, -0.35427927, -0.89425598],
       [-0.1090231 , -2.88288629,  1.8476014 ,  0.80132468],
       [-0.89099819, -0.71932509,  1.55520697, -1.09703337]])

In [10]:
np.where(arr<0,-2,2)

array([[ 2,  2, -2,  2],
       [-2,  2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2,  2, -2]])