<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/MatematikStatistika.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.random.randn(5,4)
arr

array([[ 0.71722534, -0.70889158,  0.37066443,  0.82665081],
       [-0.51761982, -1.28057388,  0.21089548,  1.50212715],
       [-0.10568874,  0.28438639,  0.94407912, -0.01883667],
       [ 0.80216506,  1.18443892,  1.33870051, -0.96120984],
       [-1.77530168,  0.12657305, -0.45134947, -0.69334411]])

In [3]:
arr.sum() #massiv elementlari yig'indisi

1.7950904660684448

In [4]:
np.sum(arr)

1.7950904660684448

In [5]:
arr.sum(axis=1) #arrayning har bir qator elementlari yig'indisi

array([ 1.205649  , -0.08517107,  1.1039401 ,  2.36409464, -2.79342221])

In [6]:
arr.sum(axis=0) #arrayning har bir ustun elementlari yig'indisi

array([-0.87921984, -0.39406709,  2.41299007,  0.65538733])

In [12]:
data=np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [13]:
data.mean() # array elementlari o'rtacha qiymati

2.5

In [15]:
mean=np.sum(data)/len(data)
mean

2.5

In [16]:
arr.mean(axis=1)

array([ 0.30141225, -0.02129277,  0.27598503,  0.59102366, -0.69835555])

In [17]:
arr.mean(axis=0)

array([-0.17584397, -0.07881342,  0.48259801,  0.13107747])

**cumsum** metodi. Array elementlarining o'rniga o'zi va o'zigacha bo'lgan elementlar yig'indisi yoziladi

In [18]:
data

array([0, 1, 2, 3, 4, 5])

In [19]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15])