<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/NumPy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data1=[2,4.5,6,3] # list
arr1=np.array(data1) # array

In [ ]:
arr1

array([2. , 4.5, 6. , 3. ])

In [ ]:
data2=(4,5,7.8,1) #tuple
arr2=np.array(data2)

In [ ]:
arr2

array([4. , 5. , 7.8, 1. ])

Massiv o'lchami

**ndim**


In [ ]:
arr1.ndim # array o'lchami

1

In [ ]:
arr2.ndim

1

## Ikki va undan ortiq o'lchamli massiv yaratish

In [ ]:
data3=[[1,2,3,4],[5,6,7,8]]
arr3=np.array(data3) # array3

In [ ]:
arr3

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
data4=[[1,2,3],[4,5,6],[7,8,9]] # uch o'lchamli list
arr4=np.array(data4) #array4

In [ ]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**shape** va **size**

In [ ]:
arr3.shape # arrayning qator va ustunlarini aniqlab beradi (q,u)

(2, 4)

In [ ]:
arr3.size  # arriyning elementlari sonini aniqlab beradi

8

**zeros** va **ones**

In [ ]:
arr5=np.zeros(shape=(3,4), dtype=int) # barcha elementlari 0 ga teng bo'lgan (3,4) o'lchamli massiv
arr5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
arr6=np.ones((4,5)) # barcha elementlari 1 ga teng bo'lgan (4,5) o'lchamli massiv
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**arange** funksiyasidan foydalanish

In [ ]:
arr7=np.arange(4,20,2) # 4 dan 20 gacha bo'lgan sonlarni 2 qadam oralatib qabul qiladi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr8=np.arange(20) # 0 dan 20 gacha 1 qadam oralatib qabul qiladi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**Ma'lumot turi**

In [ ]:
arr=np.array([1,2,3], dtype=np.int32)
arr.dtype

dtype('int32')

In [ ]:
arr9=np.array([1,2,3], dtype=np.float64)
arr9

array([1., 2., 3.])

In [ ]:
arr10=np.array([1.2,3.4,5,6.7])
arr10.dtype

dtype('float64')

**astype**

In [ ]:
arr11=arr10.astype(np.int32)
arr11

array([1, 3, 5, 6], dtype=int32)