<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.random.randn(5)
arr

array([ 0.60548596,  0.080931  , -1.13518145, -0.31488102, -1.12174453])

In [8]:
np.sort(arr) # tartiblash


array([-1.13518145, -1.12174453, -0.31488102,  0.080931  ,  0.60548596])

In [9]:
re_sort=-np.sort(-arr)
re_sort

array([ 0.60548596,  0.080931  , -0.31488102, -1.12174453, -1.13518145])

In [10]:
arr2d=np.random.randn(4,5)
arr2d

array([[-1.15142933,  0.23423701, -0.20581577,  0.22280786, -0.2438245 ],
       [-0.28069999, -1.14689262, -0.43656369, -0.54913205,  0.50042148],
       [ 0.0716796 ,  2.17250247,  1.7668228 ,  0.2392708 , -0.94589842],
       [-0.46687697, -1.50743276, -0.76494245, -0.30135975,  0.89612711]])

In [12]:
row_sort=np.sort(arr2d,axis=1) # qator bo'yicha tartiblaydi
row_sort

array([[-1.15142933, -0.2438245 , -0.20581577,  0.22280786,  0.23423701],
       [-1.14689262, -0.54913205, -0.43656369, -0.28069999,  0.50042148],
       [-0.94589842,  0.0716796 ,  0.2392708 ,  1.7668228 ,  2.17250247],
       [-1.50743276, -0.76494245, -0.46687697, -0.30135975,  0.89612711]])

In [13]:
col_sort=np.sort(arr2d, axis=0)
col_sort

array([[-1.15142933, -1.50743276, -0.76494245, -0.54913205, -0.94589842],
       [-0.46687697, -1.14689262, -0.43656369, -0.30135975, -0.2438245 ],
       [-0.28069999,  0.23423701, -0.20581577,  0.22280786,  0.50042148],
       [ 0.0716796 ,  2.17250247,  1.7668228 ,  0.2392708 ,  0.89612711]])