<a href="https://colab.research.google.com/github/makhmudovamunira/DataScience_Mohirdev/blob/main/Universal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Unary** funksiyalar. Bitta argument berishi mumkin bo'lgan funksiya

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
np.log(arr[1:]) # bunda 0-elementdan tashqari barcha elementlarning natural logarifmini hisoblaydi

<ipython-input-6-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

**modf** elementlarni qoldiq va butun qismlarga ajratib beruvchi funksiya

In [7]:
arr1=np.random.randn(6)
arr1

array([-0.75039749,  0.27072574,  0.92638361, -0.79952587, -0.24648515,
       -0.42532494])

In [8]:
qoldiq, butun =np.modf(arr1)
print(qoldiq)
print(butun)

[-0.75039749  0.27072574  0.92638361 -0.79952587 -0.24648515 -0.42532494]
[-0.  0.  0. -0. -0. -0.]


**sign** element manfiy bo'lsa **-1** musbat bo'lsa **1** qaytaruvchi funksiya

In [9]:
np.sign(arr1)

array([-1.,  1.,  1., -1., -1., -1.])

**isnan** massiv elementi NaN bo'lsa **True** aks holda **False** qiymat qaytaradi

In [10]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [13]:
arr1[0]=np.NaN # 0-elemntni nan qiymatga aylantirdik
arr1

array([        nan,  0.27072574,  0.92638361, -0.79952587, -0.24648515,
       -0.42532494])

In [15]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

**Binary** ikta argument qatnashuvchi funksiya

**add** funksiyasi. Arrayning mos elementlarini qo'shuvchi funksiya

In [16]:
arr2=np.random.randn(7)
arr3=np.random.randn(7)

In [17]:
np.add(arr2,arr3)

array([ 1.19103813,  0.69737327, -0.50470766, -0.77965651, -0.61244964,
       -0.42610874,  1.0242826 ])

**multiply** funksiyasi. Arrayning mos elementlarini ko'paytirib beruvchi funksiya

In [18]:
np.multiply(arr2,arr3)

array([ 0.04963412,  0.10889172,  0.05913527, -0.27835399,  0.01505525,
        0.04379757,  0.21921036])

**maximum** funksiyasi. Arrayning mos elementlaridan kattasini tanlab oluvchi funksiya

In [19]:
np.maximum(arr2,arr3)

array([ 1.14779512,  0.46133942, -0.18492101,  0.2661596 , -0.02565685,
       -0.17312193,  0.71969455])